#!/usr/bin/env python3
"""
Pure Copilot CLI System - Document Generator
Processes YAML manifests from briefs/ for Copilot CLI generation
"""
import json
import pathlib
import sys

import jsonschema
import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
BRIEFS = ROOT / "briefs"


def validate_manifest(path):
    """Validate YAML manifest for Copilot CLI processing."""
    print(f"🧩 Validating {path.name}")
    with open(path, encoding="utf-8") as f:
        spec = yaml.safe_load(f)
    
    # Handle both project_meta structure and simple project structure
    project_name = None
    if "project_meta" in spec:
        project_name = spec["project_meta"].get("name", path.stem.replace("_Stack", ""))
    elif "project" in spec:
        project_name = spec["project"]
    else:
        # Default to filename if neither structure exists
        project_name = path.stem.replace("_Stack", "")
    
    # Basic validation - Copilot CLI can handle any valid YAML structure
    schema = {"type": "object"}  # Minimal validation for flexibility
    jsonschema.validate(spec, schema)
    
    # Add normalized project field for consistency
    spec["_normalized_project"] = project_name
    return spec


def generate_docs(spec, name):
    """Generate OpenAPI and Schema docs for Copilot CLI system."""
    out_api = ROOT / f"{name}_API_OpenAPI.yaml"
    out_schema = ROOT / f"{name}_API_Schema.json"
    
    # Use normalized project name
    project_name = spec.get("_normalized_project", name)
    
    # Extract or create basic schemas for API documentation
    components = spec.get("components", {})
    schemas = components.get("schemas", {})
    
    # If no schemas defined, create basic project schema
    if not schemas:
        schemas = {
            "Project": {
                "type": "object",
                "properties": {
                    "name": {"type": "string", "example": project_name},
                    "version": {"type": "string", "example": "1.0.0"},
                    "description": {"type": "string", "example": "Generated"}
                },
                "required": ["name", "version"]
            }
        }
    
    # Generate OpenAPI spec optimized for Copilot CLI understanding
    openapi = {
        "openapi": "3.1.0",
        "info": {
            "title": f"{project_name} API",
            "version": "1.0.0",
            "description": "Generated by Copilot CLI Factory"
        },
        "paths": {
            "/health": {
                "get": {
                    "summary": "Health check endpoint",
                    "responses": {
                        "200": {
                            "description": "Service is healthy",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/Project"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "components": {"schemas": schemas},
    }
    
    # Write files for Copilot CLI reference
    with open(out_api, "w", encoding="utf-8") as f:
        yaml.safe_dump(openapi, f, default_flow_style=False)
    with open(out_schema, "w", encoding="utf-8") as f:
        json.dump(schemas, f, indent=2)
    
    print(f"✅ Copilot CLI docs → {out_api}, {out_schema}")


def main():
    """Process YAML manifests for Copilot CLI system."""
    if len(sys.argv) > 1:
        # Process specific file from command line
        brief_path = pathlib.Path(sys.argv[1])
        if brief_path.exists():
            name = brief_path.stem.replace("_Stack", "")
            spec = validate_manifest(brief_path)
            generate_docs(spec, name)
            print(f"✅ Processed {brief_path.name} for Copilot CLI")
        else:
            print(f"❌ File not found: {brief_path}")
            sys.exit(1)
    else:
        # Process all files in briefs directory
        for brief in BRIEFS.glob("*_Stack.yaml"):
            name = brief.stem.replace("_Stack", "")
            spec = validate_manifest(brief)
            generate_docs(spec, name)
            print(f"� Ready for Copilot CLI: {name}")


if __name__ == "__main__":
    main()
